# fly.toml app configuration file generated for mfojtikio on 2023-08-21T15:44:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mfojtikio"
primary_region = "ams"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
